### ISSUE TITLE
'NODE_ENV' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by NabiKAZ** [legendecas/material-swagger-ui#2]
I run `npm install`
And run `npm run dist` give me this error:
```
> material-swagger-ui@0.1.1 dist C:\Users\Nabi\Compressed\material-swagger-ui-0.1.1\material-swagger-ui-0.1.1
> NODE_ENV=production webpack

'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! material-swagger-ui@0.1.1 dist: `NODE_ENV=production webpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the material-swagger-ui@0.1.1 dist script 'NODE_ENV=production webpack'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the material-swagger-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=production webpack
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs material-swagger-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls material-swagger-ui
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Nabi\AppData\Roaming\npm-cache\_logs\2017-04-14T09_44_13_652Z-debug.log
```

And so check `NODE_ENV`:
```
>echo %NODE_ENV%
production webpack
```
How can I use this program?

**Comment by legendecas** [comment]
Well, you can try `set NODE_ENV=production` then `webpack` instead on windows.
I'll update the script later.
Also, you can try to build this project on Windows subsystem for Linux, which is perfectly compatible with Unix-style commands.

**Comment by NabiKAZ** [comment]
Not works.

I try git bash linux style in windows but does not work:
```
Nabi@NabiKAZ2 MINGW64 ~/Compressed/material-swagger-ui-0.1.1/material-swagger-ui-0.1.1
$ echo $NODE_ENV
production webpack

Nabi@NabiKAZ2 MINGW64 ~/Compressed/material-swagger-ui-0.1.1/material-swagger-ui-0.1.1
$ npm run dist

> material-swagger-ui@0.1.1 dist C:\Users\Nabi\Compressed\material-swagger-ui-0.1.1\material-swagger-ui-0.1.1
> NODE_ENV=production webpack

'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dist"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! material-swagger-ui@0.1.1 dist: `NODE_ENV=production webpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the material-swagger-ui@0.1.1 dist script 'NODE_ENV=production webpack'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the material-swagger-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=production webpack
npm ERR! You can get their info via:
npm ERR!     npm owner ls material-swagger-ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Nabi\Compressed\material-swagger-ui-0.1.1\material-swagger-ui-0.1.1\npm-debug.log
```

I thinks it's better provide `dist` in your releases packages.

**Comment by legendecas** [comment]
I mean that set `NODE_ENV` to `production` and then run `webpack` directly but not `npm run dist`.

**Comment by NabiKAZ** [comment]
I thinks `webpack` not installed on my system! I install webpack and get this error:
```
>node run dist
module.js:328
    throw err;
    ^

Error: Cannot find module 'C:\Users\Nabi\Compressed\material-swagger-ui-0.1.1\material-swagger-ui-0.1.1\run'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3
```

So I try just `webpack` command:
```
>webpack
Hash: 850b40d9d8a3392104a6
Version: webpack 1.15.0
Time: 124072ms
                                                     Asset     Size  Chunks             Chunk Names
  font/Roboto-Regular.df7b648ce5356ea1ebce435b3459fd60.ttf   126 kB          [emitted]
     font/Roboto-Thin.dfe56a876d0282555d1e2458e278060f.eot  21.7 kB          [emitted]
    font/Roboto-Thin.7500519de3d82e33d1587f8042e2afcb.woff  61.6 kB          [emitted]
     font/Roboto-Thin.94998475f6aea65f558494802416c1cf.ttf   128 kB          [emitted]
    font/Roboto-Light.a990f611f2305dc12965f186c2ef2690.eot  20.9 kB          [emitted]
  font/Roboto-Light.69f8a0617ac472f78e45841323a3df9e.woff2  49.4 kB          [emitted]
   font/Roboto-Light.3b813c2ae0d04909a33a18d792912ee7.woff  62.3 kB          [emitted]
    font/Roboto-Light.46e48ce0628835f68a7369d0254e4283.ttf   127 kB          [emitted]
  font/Roboto-Regular.30799efa5bf74129468ad4e257551dc3.eot  21.3 kB          [emitted]
font/Roboto-Regular.2751ee43015f9884c3642f103b7f70c9.woff2  49.2 kB          [emitted]
 font/Roboto-Regular.ba3dcd8903e3d0af5de7792777f8ae0d.woff  61.7 kB          [emitted]
   font/Roboto-Thin.954bbdeb86483e4ffea00c4591530ece.woff2  48.5 kB          [emitted]
   font/Roboto-Medium.4d9f3f9e5195e7b074bb63ba4ce42208.eot  21.4 kB          [emitted]
 font/Roboto-Medium.574fd0b50367f886d359e8264938fc37.woff2  50.2 kB          [emitted]
  font/Roboto-Medium.fc78759e93a6cac50458610e3d9d63a0.woff    63 kB          [emitted]
   font/Roboto-Medium.894a2ede85a483bf9bedefd4db45cdb9.ttf   127 kB          [emitted]
     font/Roboto-Bold.ecdd509cadbf1ea78b8d2e31ec52328c.eot    21 kB          [emitted]
   font/Roboto-Bold.39b2c3031be6b4ea96e2e3e95d307814.woff2    50 kB          [emitted]
    font/Roboto-Bold.dc81817def276b4f21395f7ea5e88dcd.woff  62.9 kB          [emitted]
     font/Roboto-Bold.e31fcf1885e371e19f5786c2bdfeae1b.ttf   128 kB          [emitted]
                                        js/index.bundle.js  2.98 MB       0  [emitted]  index
                                    js/index.bundle.js.map  3.57 MB       0  [emitted]  index
   [0] multi index 28 bytes {0} [built]
    + 686 hidden modules
```

It works fine and I have `dist` folder now.
But just `js` and `font` folders is in here.
How can I use this?!

**Comment by legendecas** [comment]
Just open `index.html` under the project's root in your browser and there it is. :)

**Comment by NabiKAZ** [comment]
Thanks, It's beautiful.
